export const dashboardStats = [
  {
    title: "Total Test Runs",
    value: "2,830",
    change: "+12%",
  },
  {
    title: "Failed Tests",
    value: "97",
    change: "-5%",
  },
  {
    title: "Healed Tests",
    value: "64",
    change: "+18%",
  },
  {
    title: "Flaky Tests",
    value: "34",
    change: "+7%",
  },
];

export const recentFailures = [
  {
    id: "F001",
    testName: "Login Test",
    pipeline: "GitHub Actions",
    rootCause: "Locator Issue",
    status: "FAIL",
    healing: "Suggested",
    confidence: "91%",
    logs: "Element not found using selector #login-btn",
    stackTrace: "NoSuchElementException at LoginPage.submit()",
    screenshot: "/placeholder.png",
    recommendation: "Update locator using stable attribute data-testid='login-button'",
    developerAlert: false,
  },
  {
    id: "F002",
    testName: "Checkout Test",
    pipeline: "Jenkins",
    rootCause: "Synchronization Issue",
    status: "FAIL",
    healing: "Applied",
    confidence: "87%",
    logs: "Timeout while waiting for payment modal",
    stackTrace: "TimeoutException at CheckoutPage.confirmPayment()",
    screenshot: "/placeholder.png",
    recommendation: "Increase explicit wait and wait for modal visibility",
    developerAlert: false,
  },
  {
    id: "F003",
    testName: "Profile Update Test",
    pipeline: "GitLab CI",
    rootCause: "Environment Failure",
    status: "FAIL",
    healing: "Pending",
    confidence: "84%",
    logs: "Database connection refused during profile save",
    stackTrace: "ConnectionError at ProfileService.updateProfile()",
    screenshot: "/placeholder.png",
    recommendation: "Re-run after verifying test environment database service",
    developerAlert: true,
  },
  {
    id: "F004",
    testName: "Cart Validation Test",
    pipeline: "GitHub Actions",
    rootCause: "Assertion Error",
    status: "FAIL",
    healing: "Rejected",
    confidence: "79%",
    logs: "Expected total price 250 but found 230",
    stackTrace: "AssertionError at CartTest.validateTotal()",
    screenshot: "/placeholder.png",
    recommendation: "Review expected value and validate business rule change",
    developerAlert: true,
  },
];

export const healingActions = [
  {
    id: "H001",
    failureId: "F001",
    testName: "Login Test",
    repairType: "Locator Repair",
    oldValue: "#login-btn",
    newValue: "[data-testid='login-button']",
    status: "Suggested",
  },
  {
    id: "H002",
    failureId: "F002",
    testName: "Checkout Test",
    repairType: "Wait Strategy Update",
    oldValue: "wait(2000)",
    newValue: "waitForElementVisible('.payment-modal', 10000)",
    status: "Applied",
  },
  {
    id: "H003",
    failureId: "F003",
    testName: "Profile Update Test",
    repairType: "Environment Retry",
    oldValue: "single execution",
    newValue: "retry after DB health check",
    status: "Pending",
  },
];

export const flakyTests = [
  {
    id: "T001",
    testName: "Login Test",
    instabilityScore: "82%",
    recentPattern: "PASS, FAIL, PASS, FAIL, PASS",
    riskLevel: "High",
  },
  {
    id: "T002",
    testName: "Checkout Test",
    instabilityScore: "64%",
    recentPattern: "PASS, PASS, FAIL, PASS, FAIL",
    riskLevel: "Medium",
  },
  {
    id: "T003",
    testName: "Search Test",
    instabilityScore: "38%",
    recentPattern: "PASS, PASS, PASS, FAIL, PASS",
    riskLevel: "Low",
  },
];